services:
  frontend:
    image: kalyonekenobe/funders:frontend
    platform: linux/amd64
    build:
      dockerfile: Dockerfile.production
    container_name: funders-frontend
    networks:
      - funders-network
    env_file:
      - ./env/.env.production
    environment:
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
      NEXT_PUBLIC_FRONTEND_URL: ${NEXT_PUBLIC_FRONTEND_URL}
      NEXT_PUBLIC_DEFAULT_PROFILE_IMAGE_PATH: ${NEXT_PUBLIC_DEFAULT_PROFILE_IMAGE_PATH}
      NEXT_PUBLIC_POST_IMAGE_PLACEHOLDER_PATH: ${NEXT_PUBLIC_POST_IMAGE_PLACEHOLDER_PATH}
      NEXT_PUBLIC_PROFILE_IMAGE_PLACEHOLDER_PATH: ${NEXT_PUBLIC_PROFILE_IMAGE_PLACEHOLDER_PATH}
      NEXT_PUBLIC_PROFILE_BACKGROUND_PLACEHOLDER_PATH: ${NEXT_PUBLIC_PROFILE_BACKGROUND_PLACEHOLDER_PATH}
      NEXT_PUBLIC_STRIPE_PUBLIC_KEY: ${NEXT_PUBLIC_STRIPE_PUBLIC_KEY}
      NEXT_AUTH_MESSAGE_TEMPLATE: ${NEXT_AUTH_MESSAGE_TEMPLATE}
      NEXT_COOKIE_ACCESS_TOKEN_NAME: ${NEXT_COOKIE_ACCESS_TOKEN_NAME}
      NEXT_COOKIE_REFRESH_TOKEN_NAME: ${NEXT_COOKIE_REFRESH_TOKEN_NAME}
      NEXT_COOKIE_OAUTH2_TOKEN_NAME: ${NEXT_COOKIE_OAUTH2_TOKEN_NAME}
      NEXT_COOKIE_ACCOUNT_COMPLETION_TOKEN_NAME: ${NEXT_COOKIE_ACCOUNT_COMPLETION_TOKEN_NAME}
      NEXT_JWT_SECRET: ${NEXT_JWT_SECRET}
      NEXT_JWT_ISSUER: ${NEXT_JWT_ISSUER}
      NEXT_JWT_AUDIENCE: ${NEXT_JWT_AUDIENCE}
      NEXT_JWT_ACCESS_TOKEN_DURATION: ${NEXT_JWT_ACCESS_TOKEN_DURATION}
      NEXT_JWT_REFRESH_TOKEN_DURATION: ${NEXT_JWT_REFRESH_TOKEN_DURATION}
      NEXT_JWT_REFRESH_TOKEN_EXTENDED_DURATION: ${NEXT_JWT_REFRESH_TOKEN_EXTENDED_DURATION}
    ports:
      - 3000:${DOCKER_INTERNAL_FRONTEND_PORT}
    volumes:
      - ./src:/app/src
    deploy:
      resources:
        limits:
          memory: 2048M
    restart: on-failure

networks:
  funders-network:
    driver: bridge
